language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '8'
script:
  - npm test
  - npm run build
after_success:
  - npm run codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: npm release
      if: branch = master
      script: npm run semantic-release