language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '8'
jobs:
  stages:
    - test
    - codecov
    - build
    - release
  include:
    - stage: test
      script: npm test
    - stage: codecov
      script: npm run codecov
    - stage: build
      script: npm run build
    - stage: release
      if: branch = master
      script: npm run semantic-release